<a href="https://colab.research.google.com/github/Mia-Tay/collab_housing/blob/main/housing_price_part1_3_economicData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
folder= 'drive/My Drive/learning/'

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option("display.expand_frame_repr", False)

In [ ]:
#open excel file demographics
df = pd.read_excel(folder+'demographics-nhs-indicators-2011.xlsx').copy()
df.head()

  Hood# Total Population Child0-14 Youth15-24 Seniors65   Total visible minority population     South Asian     Chinese     Black     Filipino     Latin American      Arab     Southeast Asian     West Asian     Korean     Japanese     Visible minority, n.i.e.     Multiple visible minorities   Not a visible minority Total - Mobility status 5 years ago   Non-movers   Movers Total recent immigrant population in private households by selected places of birth Middle East/Western Asia     Eastern  South East    Southern      Other places of birth in Asia Americas w/o USA      Europe      Africa Total population aged 15 years and over by labour force status    In the labour force      Unemployed   Not in the labour force   No certificate, diploma or degree     College, CEGEP or other non-university certificate or diploma     University certificate or diploma below bachelor level Total number of private households by tenure      Owner     Renter   % of owner households spending 30% or more of household total income on shelter costs   Major repairs needed   Average monthly shelter costs for rented dwellings ($)   Average after-tax family income $ (Family income in 2010 of economic families) Household income in 2010 of private households   Median household total income $   Median after-tax household income $
0    ID           popt01   popt201    popt202   popt204                            vismin01        vismin04    vismin05  vismin03     vismin09           vismin11  vismin15            vismin08       vismin16   vismin06     vismin07                     vismin14                        vismin13                 vismin17                              res5_1       res1_2   res1_3                                          recbirth1                                                recbirth68  recbirth69  recbirth73  recbirth76                                NaN       recbirth51  recbirth52  recbirth61                                            plf15_1                             plf15_2        plf15_4                   plf15_5                           higheda02                                          higheda03                                                         higheda09                                            occprdw20  occprdw05  occprdw06                                          shelter30                                                   occprdw11                                          occprdw21                                                infamtx12                                                                    incprhh01                         incprhh14                             incprhh58
1     1            34100      5970       5405      4305                               26475           13080         695      6385         1470               1220       235                 820            220        100           55                         1615                             580                     6855                               31460        20635    10820                                               2750                                                         0          65         250        1495                               40.0              530          40         260                                              27365                               17610           1750                      9755                                6170                                               4375                                                              1445                                                10130       7075       3050                                               27.9                                                         415                                                945                                                    72820                                                                        10130                             66241                                 59703
2     2            32790      7665       5020      2945                               28175           12720         200      8285          680                870      1605                 560           1160         85            0                         1565                             435                     4525                               30105        16210    13895                                               5850                                                      1380           0         120        2625                               30.0              710          75         830                                              24980                               14655           2175                     10320                                6855                                               3325                                                              1090                                                 9610       4540       5070                                               33.3                                                        1100                                                921                                                    57411                                                                         9610                             49934                                 46986
3     3            10140      1825       1350      1745                                6285            2285         105      1530          485                670       210                 200            285          0           10                          225                             275                     3705                                9380         6290     3085                                               1070                                                       195           0          80         400                                0.0              190          15         130                                               8135                                4825            530                      3315                                1970                                               1180                                                               650                                                 3225       2080       1145                                               25.1                                                         170                                                887                                                    70838                                                                         3225                             62042                                 57522
4     4            10485      1585       1315      1915                                4425            1435         200      1025          245                650        55                  85             40         90           50                          385                             175                     5735                                9705         6890     2815                                                800                                                         0          35          20         405                                0.0              255          50           0                                               8600                                5270            590                      3330                                2095                                               1450                                                               350                                                 3945       2010       1935                                               19.7                                                         340                                                857                                                    69367                                                                         3945                             56545                                 51194

In [ ]:
#use first row as header
header = df.columns
df.columns=header.str.lstrip(' ')
df = df.iloc[1:,:]
df.head()

  Hood# Total Population Child0-14 Youth15-24 Seniors65 Total visible minority population South Asian Chinese Black Filipino Latin American  Arab Southeast Asian West Asian Korean Japanese Visible minority, n.i.e. Multiple visible minorities Not a visible minority Total - Mobility status 5 years ago Non-movers Movers Total recent immigrant population in private households by selected places of birth Middle East/Western Asia Eastern South East Southern  Other places of birth in Asia Americas w/o USA Europe Africa Total population aged 15 years and over by labour force status  In the labour force  Unemployed Not in the labour force No certificate, diploma or degree College, CEGEP or other non-university certificate or diploma University certificate or diploma below bachelor level Total number of private households by tenure Owner Renter % of owner households spending 30% or more of household total income on shelter costs Major repairs needed Average monthly shelter costs for rented dwellings ($) Average after-tax family income $ (Family income in 2010 of economic families) Household income in 2010 of private households Median household total income $ Median after-tax household income $
1     1            34100      5970       5405      4305                             26475       13080     695  6385     1470           1220   235             820        220    100       55                     1615                         580                   6855                               31460      20635  10820                                               2750                                                         0      65        250     1495                           40.0              530     40    260                                              27365                             17610       1750                    9755                              6170                                               4375                                                          1445                                            10130  7075   3050                                               27.9                                                     415                                                945                                                  72820                                                                      10130                           66241                               59703
2     2            32790      7665       5020      2945                             28175       12720     200  8285      680            870  1605             560       1160     85        0                     1565                         435                   4525                               30105      16210  13895                                               5850                                                      1380       0        120     2625                           30.0              710     75    830                                              24980                             14655       2175                   10320                              6855                                               3325                                                          1090                                             9610  4540   5070                                               33.3                                                    1100                                                921                                                  57411                                                                       9610                           49934                               46986
3     3            10140      1825       1350      1745                              6285        2285     105  1530      485            670   210             200        285      0       10                      225                         275                   3705                                9380       6290   3085                                               1070                                                       195       0         80      400                            0.0              190     15    130                                               8135                              4825        530                    3315                              1970                                               1180                                                           650                                             3225  2080   1145                                               25.1                                                     170                                                887                                                  70838                                                                       3225                           62042                               57522
4     4            10485      1585       1315      1915                              4425        1435     200  1025      245            650    55              85         40     90       50                      385                         175                   5735                                9705       6890   2815                                                800                                                         0      35         20      405                            0.0              255     50      0                                               8600                              5270        590                    3330                              2095                                               1450                                                           350                                             3945  2010   1935                                               19.7                                                     340                                                857                                                  69367                                                                       3945                           56545                               51194
5     5             9550      2110       1380      1095                              5510         925     120  2150      605            695    80             400        265     55        0                       70                         145                   4030                                8935       6200   2740                                                545                                                        30       0         50       80                            0.0              205     55     90                                               7495                              4640        575                    2850                              2025                                               1395                                                           260                                             3225  1910   1315                                               34.3                                                     320                                                966                                                  61196                                                                       3225                           50846                               49425

In [ ]:
#create new columns that indicate percentage of features
df['minority_perc'] = df['Total visible minority population']/df['Total Population']
df['South Asian%'] = df['South Asian']/df['Total Population']
df['Chinese%'] = df['Chinese']/df['Total Population']
df['Black%'] = df['Black']/df['Total Population']
df['west_asian%']= df['West Asian']/df['Total Population']
df['latin_american%'] = df['Latin American'] /df['Total Population']
df['unemployment%'] = df['Unemployed'] / df['Total Population']
df['no_college'] = df['No certificate, diploma or degree'] /df['Total Population']
df['owner%']= df['Owner'] / (df['Owner']+df['Renter'])
df['renter%'] = df['Renter']/(df['Owner']+df['Renter'])

In [ ]:
df.head()

  Hood# Total Population Child0-14 Youth15-24 Seniors65 Total visible minority population South Asian Chinese Black Filipino Latin American  Arab Southeast Asian West Asian Korean Japanese Visible minority, n.i.e. Multiple visible minorities Not a visible minority Total - Mobility status 5 years ago Non-movers Movers Total recent immigrant population in private households by selected places of birth Middle East/Western Asia Eastern South East Southern  Other places of birth in Asia Americas w/o USA Europe Africa Total population aged 15 years and over by labour force status  In the labour force  Unemployed Not in the labour force No certificate, diploma or degree College, CEGEP or other non-university certificate or diploma University certificate or diploma below bachelor level Total number of private households by tenure Owner Renter % of owner households spending 30% or more of household total income on shelter costs Major repairs needed Average monthly shelter costs for rented dwellings ($) Average after-tax family income $ (Family income in 2010 of economic families) Household income in 2010 of private households Median household total income $ Median after-tax household income $ minority_perc South Asian%    Chinese%     Black% west_asian% latin_american% unemployment% no_college    owner%   renter%
1     1            34100      5970       5405      4305                             26475       13080     695  6385     1470           1220   235             820        220    100       55                     1615                         580                   6855                               31460      20635  10820                                               2750                                                         0      65        250     1495                           40.0              530     40    260                                              27365                             17610       1750                    9755                              6170                                               4375                                                          1445                                            10130  7075   3050                                               27.9                                                     415                                                945                                                  72820                                                                      10130                           66241                               59703      0.776393     0.383578   0.0203812   0.187243  0.00645161       0.0357771     0.0513196   0.180938  0.698765  0.301235
2     2            32790      7665       5020      2945                             28175       12720     200  8285      680            870  1605             560       1160     85        0                     1565                         435                   4525                               30105      16210  13895                                               5850                                                      1380       0        120     2625                           30.0              710     75    830                                              24980                             14655       2175                   10320                              6855                                               3325                                                          1090                                             9610  4540   5070                                               33.3                                                    1100                                                921                                                  57411                                                                       9610                           49934                               46986      0.859256     0.387923  0.00609942   0.252668   0.0353766       0.0265325     0.0663312   0.209058  0.472425  0.527575
3     3            10140      1825       1350      1745                              6285        2285     105  1530      485            670   210             200        285      0       10                      225                         275                   3705                                9380       6290   3085                                               1070                                                       195       0         80      400                            0.0              190     15    130                                               8135                              4825        530                    3315                              1970                                               1180                                                           650                                             3225  2080   1145                                               25.1                                                     170                                                887                                                  70838                                                                       3225                           62042                               57522      0.619822     0.225345    0.010355   0.150888   0.0281065        0.066075     0.0522682    0.19428  0.644961  0.355039
4     4            10485      1585       1315      1915                              4425        1435     200  1025      245            650    55              85         40     90       50                      385                         175                   5735                                9705       6890   2815                                                800                                                         0      35         20      405                            0.0              255     50      0                                               8600                              5270        590                    3330                              2095                                               1450                                                           350                                             3945  2010   1935                                               19.7                                                     340                                                857                                                  69367                                                                       3945                           56545                               51194      0.422031     0.136862   0.0190749  0.0977587  0.00381497       0.0619933     0.0562709   0.199809  0.509506  0.490494
5     5             9550      2110       1380      1095                              5510         925     120  2150      605            695    80             400        265     55        0                       70                         145                   4030                                8935       6200   2740                                                545                                                        30       0         50       80                            0.0              205     55     90                                               7495                              4640        575                    2850                              2025                                               1395                                                           260                                             3225  1910   1315                                               34.3                                                     320                                                966                                                  61196                                                                       3225                           50846                               49425      0.576963    0.0968586   0.0125654   0.225131   0.0277487       0.0727749     0.0602094   0.212042  0.592248  0.407752

In [ ]:
#drop extra not helpful columns
df_demo = df.drop(df.loc[:,'Child0-14':'Renter'], axis=1)
df_demo.drop(columns=['Major repairs needed','Median after-tax household income $'],inplace=True)
df_demo.head()

  Hood# Total Population % of owner households spending 30% or more of household total income on shelter costs Average monthly shelter costs for rented dwellings ($) Average after-tax family income $ (Family income in 2010 of economic families) Household income in 2010 of private households Median household total income $ minority_perc South Asian%    Chinese%     Black% west_asian% latin_american% unemployment% no_college    owner%   renter%
1     1            34100                                               27.9                                                                                   945                                                  72820                                                                      10130                           66241      0.776393     0.383578   0.0203812   0.187243  0.00645161       0.0357771     0.0513196   0.180938  0.698765  0.301235
2     2            32790                                               33.3                                                                                   921                                                  57411                                                                       9610                           49934      0.859256     0.387923  0.00609942   0.252668   0.0353766       0.0265325     0.0663312   0.209058  0.472425  0.527575
3     3            10140                                               25.1                                                                                   887                                                  70838                                                                       3225                           62042      0.619822     0.225345    0.010355   0.150888   0.0281065        0.066075     0.0522682    0.19428  0.644961  0.355039
4     4            10485                                               19.7                                                                                   857                                                  69367                                                                       3945                           56545      0.422031     0.136862   0.0190749  0.0977587  0.00381497       0.0619933     0.0562709   0.199809  0.509506  0.490494
5     5             9550                                               34.3                                                                                   966                                                  61196                                                                       3225                           50846      0.576963    0.0968586   0.0125654   0.225131   0.0277487       0.0727749     0.0602094   0.212042  0.592248  0.407752

In [ ]:
#read new excel file and use first row as header
df_eco = pd.read_excel(folder+'wellbeing-toronto-economics.xlsx').copy()
header = df_eco.iloc[0,:]
header
df_eco.columns = header
df_eco = df_eco.iloc[1:,:]
df_eco

0                        Neighbourhood Neighbourhood Id Businesses Child Care Spaces Debt Risk Score Home Prices Local Employment Social Assistance Recipients
1               West Humber-Clairville                1       2463               195             719      317508            58271                         2912
2    Mount Olive-Silverstone-Jamestown                2        271                60             687      251119             3244                         6561
3         Thistletown-Beaumond Heights                3        217                25             718      414216             1311                         1276
4                      Rexdale-Kipling                4        144                75             721      392271             1178                         1323
5                     Elms-Old Rexdale                5         67                60             692      233832              903                         1683
6        Kingsview Village-The Westway                6        160               129             717      292861             2799                         4348
7     Willowridge-Martingrove-Richview                7        169               165             750      511637             1843                         2032
8             Humber Heights-Westmount                8         82               140             753      491396              896                          856
9             Edenbridge-Humber Valley                9        153                30             761      873268             1334                          751
10                  Princess-Rosethorn               10         74               367             791      971668             1226                          299
11      Eringate-Centennial-West Deane               11        229               172             775      423034             3472                          775
12                       Markland Wood               12        106               105             783      505350             1494                          239
13                 Etobicoke West Mall               13        146                60             738      298426             4340                         1091
14          Islington-City Centre West               14       2263               204             755      491678            45794                         2534
15                      Kingsway South               15        195               115             793      941223             2335                           74
16                 Stonegate-Queensway               16        595               283             760      690949             5932                         1593
17                              Mimico               17        619               195             741      429941            11549                         2634
18                         New Toronto               18        368                90             719      460811             5289                         1600
19                         Long Branch               19        170                54             724      459088             1143                         1024
20                           Alderwood               20        309               120             764      504233             4839                          516
21                       Humber Summit               21       1373                53             715      354381            17950                         1659
22                          Humbermede               22        374                55             695      314721             5799                         2590
23                Pelmo Park-Humberlea               23        152                 0             735      412618             2855                          798
24                         Black Creek               24        306               175             661                         3856                         6408
25              Glenfield-Jane Heights               25        587               173             678      304262             8323                         7263
26                Downsview-Roding-CFB               26        985               238             692      400486            20150                         5618
27             York University Heights               27       2643               156             698      359372            42885                         4720
28                              Rustic               28         48                26             692      493442              550                         1924
29                          Maple Leaf               29         47                90             721      540741              737                          919
30                 Brookhaven-Amesbury               30        466                54             687      352428             4825                         3420
31                  Yorkdale-Glen Park               31       1468                82             729      421045            24685                         1502
32                 Englemount-Lawrence               32        175               105             730      577889             3495                         2733
33                        Clanton Park               33        357               130             740      605585             5011                          734
34                      Bathurst Manor               34        244               105             745      568877             3370                         1018
35                 Westminster-Branson               35         83                45             730      372380             3027                         2906
36                    Newtonbrook West               36        483                98             737      557468             9091                         2124
37                     Willowdale West               37        363               248             766      541247             7110                          515
38                    Lansing-Westgate               38        488                75             758      646460            12254                          468
39                Bedford Park-Nortown               39        676                60             776     1191040             8187                          484
40                St.Andrew-Windfields               40        591               124             774     1363202            13023                          606
41   Bridle Path-Sunnybrook-York Mills               41         58                 0             788     1849084            11756                           37
42                   Banbury-Don Mills               42        834               255             776      613647            25614                         1030
43                    Victoria Village               43        431               134             730      365107             7035                         2593
44                     Flemingdon Park               44        185               203             721      204104             5088                         4348
45                   Parkwoods-Donalda               45        209               441             731      553698             2802                         3664
46                       Pleasant View               46        124                90             767      463859             1162                          791
47                  Don Valley Village               47        373               229             756      478489             5640                         2137
48                   Hillcrest Village               48        424               180             775      484743            11806                          694
49               Bayview Woods-Steeles               49         93               180             777      784397             2207                          666
50                    Newtonbrook East               50        400                30             757      626626             4357                          685
51                     Willowdale East               51        849               209             759      540911            16026                         1189
52                     Bayview Village               52        460                60             768      533089             9377                          626
53                          Henry Farm               53        717               105             736      372110            18728                         1502
54                   O'Connor-Parkview               54        346                75             725      538203             4677                         2984
55                    Thorncliffe Park               55        449                21             724      313618             9847                         3818
56                  Leaside-Bennington               56        313               274             791     1071823             2901                          239
57                     Broadview North               57        129                57             728      518555             1286                         1306
58                       Old East York               58        134                88             756      581398             1017                          569
59                  Danforth-East York               59        167               214             763      518568             3715                         1049
60                    Woodbine-Lumsden               60         56                95             748      440700              558                          582
61                       Taylor-Massey               61        157                60             721      254151             1399                         2635
62                   East End-Danforth               62        516               330             741      535867             3636                         1901
63                         The Beaches               63        531               167             764      751945             5694                          672
64                   Woodbine Corridor               64        146               214             749      521549             1896                          906
65                   Greenwood-Coxwell               65        315                94             738      490920             2342                         1762
66                            Danforth               66        414               152             755      585093             2786                          626
67            Playter Estates-Danforth               67        301               162             757      842668             2243                          288
68                     North Riverdale               68        327               233             767      818592             4033                          503
69                         Blake-Jones               69        133                30             739      571246             1789                         1021
70                     South Riverdale               70       1197               224             746      537087            12378                         2695
71     Cabbagetown-South St.James Town               71        290                 0             744      537025             2513                          986
72                         Regent Park               72        143                30             701      484444             1931                         2491
73                           Moss Park               73        841               110             709      457524            12051                         3510
74                 North St.James Town               74        243                55             705      489366             6705                         2681
75               Church-Yonge Corridor               75       2443                45             736      410703            54044                         3090
76                 Bay Street Corridor               76       4324                30             755      457787           185891                          678
77   Waterfront Communities-The Island               77       2899               130             748      416759            88058                         2864
78                Kensington-Chinatown               78       1883               247             728      477989            37205                         2523
79                          University               79        483                15             748      773920            10967                          259
80             Palmerston-Little Italy               80        521               159             742      781568             3262                          665
81                   Trinity-Bellwoods               81        715               332             742      723909             5380                         1415
82                             Niagara               82        591                65             747      398281            15621                         1246
83                      Dufferin Grove               83        375                80             721      502736             4072                         1303
84                     Little Portugal               84        344                55             727      514960             2597                          983
85                      South Parkdale               85        564                70             695      500054             7617                         4473
86                        Roncesvalles               86        540               150             741      581425             2885                         2268
87                   High Park-Swansea               87        448               229             770      622206             6594                         1680
88                     High Park North               88        254               241             759      609689             2577                         1054
89        Runnymede-Bloor West Village               89        334               220             777      666204             2421                          251
90                       Junction Area               90        631                30             733      532997             6528                         1155
91                  Weston-Pellam Park               91        178                84             698      382119             1214                         1754
92              Corso Italia-Davenport               92        420               105             708      502819             2111                         1294
93   Dovercourt-Wallace Emerson-Juncti               93        890               179             719      512789             5077                         3563
94                            Wychwood               94        379                84             745      656868             5143                          911
95                               Annex               95       2328               201             755      993491            25719                         1150
96                           Casa Loma               96        258               142             771     1083381             3283                          189
97                      Yonge-St.Clair               97        468                20             771      995616             7858                          283
98                 Rosedale-Moore Park               98        683               162             777     1265389            19160                          499
99                 Mount Pleasant East               99        463                82             777      815247             4741                          288
100                     Yonge-Eglinton              100        690                45             759      975449            11746                          189
101                  Forest Hill South              101        175                30             775     1585984             1945                          134
102                  Forest Hill North              102        144               110             749      957688              897                          633
103                Lawrence Park South              103        167               140             784     1215390             1634                          240
104                Mount Pleasant West              104       1129               255             753      520032            13311                         1343
105                Lawrence Park North              105        381               212             790      980831             3624                          166
106                 Humewood-Cedarvale              106        139               108             747      800442             1345                          698
107                    Oakwood Village              107        255               168             713      482040             1573                         2412
108               Briar Hill-Belgravia              108        477                25             719      373937             3446                         1432
109                 Caledonia-Fairbank              109         92                75             700      400532              944                         1153
110           Keelesdale-Eglinton West              110        266                25             707      373029             1644                         1653
111                  Rockcliffe-Smythe              111        314               110             710      353967             3345                         3422
112            Beechborough-Greenbrook              112        128                22             677      440179             4140                         1478
113                             Weston              113        536               157             679      280187             4578                         4149
114                 Lambton Baby Point              114         66                19             749      806452              438                         1049
115                       Mount Dennis              115        184               109             680      273418             2198                         2937
116                            Steeles              116        237               105             778      440688             5835                         1549
117                         L'Amoreaux              117        443               126             758      355438             4734                         3848
118             Tam O'Shanter-Sullivan              118        343               192             756      411143             3882                         1973
119                   Wexford/Maryvale              119        945               140             735      422689            16717                         3014
120                Clairlea-Birchmount              120        831                84             741      387912            15391                         2688
121                           Oakridge              121        201                54             704      347446             1768                         2967
122              Birchcliffe-Cliffside              122        345               110             747      522905             3228                         1789
123                         Cliffcrest              123        200                70             748      542218             2132                         1342
124                       Kennedy Park              124        261                82             729      293600             1824                         2583

In [ ]:
#combine two dataframes
table = df_demo.merge(df_eco, how='inner', left_on='Hood#', right_on='Neighbourhood Id',copy=True, sort= True)
table.head()
table.drop(columns=['Neighbourhood Id'], inplace=True)

In [ ]:
table.to_csv(folder+'economic_hoods.csv')

In [ ]:
table.head()

  Hood# Total Population % of owner households spending 30% or more of household total income on shelter costs Average monthly shelter costs for rented dwellings ($) Average after-tax family income $ (Family income in 2010 of economic families) Household income in 2010 of private households Median household total income $ minority_perc South Asian%    Chinese%     Black% west_asian% latin_american% unemployment% no_college    owner%   renter%                      Neighbourhood Businesses Child Care Spaces Debt Risk Score Home Prices Local Employment Social Assistance Recipients
0     1            34100                                               27.9                                                                                   945                                                  72820                                                                      10130                           66241      0.776393     0.383578   0.0203812   0.187243  0.00645161       0.0357771     0.0513196   0.180938  0.698765  0.301235             West Humber-Clairville       2463               195             719      317508            58271                         2912
1     2            32790                                               33.3                                                                                   921                                                  57411                                                                       9610                           49934      0.859256     0.387923  0.00609942   0.252668   0.0353766       0.0265325     0.0663312   0.209058  0.472425  0.527575  Mount Olive-Silverstone-Jamestown        271                60             687      251119             3244                         6561
2     3            10140                                               25.1                                                                                   887                                                  70838                                                                       3225                           62042      0.619822     0.225345    0.010355   0.150888   0.0281065        0.066075     0.0522682    0.19428  0.644961  0.355039       Thistletown-Beaumond Heights        217                25             718      414216             1311                         1276
3     4            10485                                               19.7                                                                                   857                                                  69367                                                                       3945                           56545      0.422031     0.136862   0.0190749  0.0977587  0.00381497       0.0619933     0.0562709   0.199809  0.509506  0.490494                    Rexdale-Kipling        144                75             721      392271             1178                         1323
4     5             9550                                               34.3                                                                                   966                                                  61196                                                                       3225                           50846      0.576963    0.0968586   0.0125654   0.225131   0.0277487       0.0727749     0.0602094   0.212042  0.592248  0.407752                   Elms-Old Rexdale         67                60             692      233832              903                         1683